name: Backfill wheels

on:
  schedule:
    # Run at 06:00 every Monday
    - cron: '0 6 * * 1'
  workflow_dispatch:

jobs:
  build_wheels:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        package_version: ['0.1.0', '0.2.0', '0.3.0']
    steps:
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel
      - name: Create directory for downloads
        run: mkdir sdists
      - name: Download sdist from PyPI
        run: pip download --no-binary :all: --no-deps pyfxr==${{ matrix.package_version }} --dest=sdists
      - name: Build wheel
        run: python -m cibuildwheel --output-dir wheelhouse sdists/*.tar.gz
        env:
          CIBW_SKIP: pp27* cp27* cp35*
          CIBW_TEST_COMMAND: pytest {project}
          CIBW_BEFORE_TEST: pip install --prefer-binary -r requirements-dev.txt
          CIBW_BUILD_VERBOSITY: 0
      - uses: pypa/gh-action-pypi-publish@v1.8.14
        with:
          user: __token__
          password: ${{ secrets.pypi_password }}
          packages-dir: wheelhouse/
